apiVersion: v1
name: grade-submission-portal
description: This is grade submission portal frontend
version: 1.0.0
appVersion: 1.0.0 # This is the version of the application enclosed inside of this Helm package. It describes changes to the application itself.