apiVersion: v1
name: grade-submission-api
description: This is grade submission api 
version: 1.0.1  # This is the Chart version. It describes changes to the Helm package itself.
appVersion: 1.0.0  # This is the version of the application enclosed inside of this Helm package. It describes changes to the application itself.