apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name}}-service
  namespace: {{ .Values.frontend.namespace}}
spec:
  type: ClusterIP
  selector:  # is used to query the pod inorder to know where to forward the traffic
    app.kubernetes.io/instance: {{ .Values.frontend.name}}
  ports:
  - port: {{ .Values.workload.port}}  # The port exposed by the Service
    targetPort: {{ .Values.workload.port}} # The port on the Pod/container where the application is actually listening.
    # A NodePort exposes the Service through a port on every Kubernetes node
    # which means service exppose this port to outside of internal cluster  http://grade-submission-portal-service:32000
    # nodePort: 32000   
