apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name}}-secret
  namespace: {{ .Values.microservice.namespace}}
type: Opaque
data:
    MONGODB_USER: {{ .Values.secret.MONGODB_USER }}
    MONGODB_PASSWORD: {{ .Values.secret.MONGODB_PASSWORD }}
